version: 2.1

jobs:
  build:
    working_directory: ~/ncnt-api
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: ncnt-api-{{ checksum "pom.xml" }}
      - run:
          name: Get maven dependancies
          command: 'mvn dependency:go-offline'
      - save_cache: # saves the project dependencies
          paths:
          - ~/.m2
          key: ncnt-api-{{ checksum "pom.xml" }}
      - run:
          name: Package latest jar
          command: 'mvn clean package -DskipTests=true'
      - persist_to_workspace:
          root: ~/ncnt-api
          paths:
            - .
  test:
    docker: # run the steps with Docker
    - image: circleci/openjdk:8-jdk-browsers
    steps:
      - attach_workspace:
          at: ~/ncnt-api
      - checkout
      - run:
          name: Run tests
          command: 'mvn test'
  deploy-dev:
    docker:
      - image: amaysim/serverless
    steps:
      - attach_workspace:
        at: ~/ncnt-api
      - run:
          name: Configure serverless aws
          command: 'serverless config credentials --provider aws --key ${AWS_ACCESS_KEY} --secret ${AWS_SECRET_KEY}'
      - run:
          name: Deploy to development
          command: 'serverless deploy --stage development'

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
  build_and_deploy:
    jobs:
    - build
    - test:
        requires:
        - build
        filters:
          branches:
            only: master
    - deploy-dev:
        requires:
          - test
        filters:
          branches:
            only: master