version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/ncnt-api
  serverless-executor:
    docker:
      - image: amaysim/serverless:1.36.3
    working_directory: ~/ncnt-api

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/ncnt-api
      - restore_cache:
          key: ncnt-api-{{ checksum "pom.xml" }}
      - run:
          name: Get maven dependancies
          command: 'mvn dependency:go-offline'
      - save_cache: # saves the project dependencies
          paths:
          - ~/.m2
          key: ncnt-api-{{ checksum "pom.xml" }}
      - run:
          name: Build, Test, and Package latest jar
          command: 'mvn clean compile assembly:single'
      - persist_to_workspace:
          root: .
          paths: target/ncent-api-dev-jar-with-dependencies.jar
  deploy-dev:
    executor: serverless-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/ncnt-api
      - run:
          name: Deploy to development
          command: 'serverless deploy --stage development'

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
  build_and_deploy:
    jobs:
    - build
    - deploy-dev:
        requires:
          - build
        filters:
          branches:
            only: master