version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: amaysim/serverless:1.36.3
    working_directory: ~/ncnt-api

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          key: ncnt-api-{{ checksum "pom.xml" }}
      - run:
          name: Get maven dependancies
          command: 'mvn dependency:go-offline'
      - save_cache: # saves the project dependencies
          paths:
          - ~/.m2
          key: ncnt-api-{{ checksum "pom.xml" }}
      - run:
          name: Package latest jar
          command: 'mvn clean package -DskipTests=true'
      - save_cache: # saves the jar file
          paths:
          - /target
          key: ncnt-api-jar-{{ checksum "pom.xml" }}
  test:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          key: ncnt-api-{{ checksum "pom.xml" }}
      - restore_cache:
          key: ncnt-api-jar-{{ checksum "pom.xml" }}
      - run:
          name: Run tests
          command: 'mvn test'
#  deploy-dev:
#    executor: my-executor
#    steps:
#      - run:
#          name: Configure serverless aws
#          command: 'serverless config credentials --provider aws --key ${AWS_ACCESS_KEY} --secret ${AWS_SECRET_KEY}'
#      - run:
#          name: Deploy to development
#          command: 'serverless deploy --stage development'

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
#  build_and_deploy:
#    jobs:
#    - build
#    - test:
#        requires:
#        - build
#        filters:
#          branches:
#            only: master
#    - deploy-dev:
#        requires:
#          - test
#        filters:
#          branches:
#            only: master